// Code generated by protoc-gen-go. DO NOT EDIT.
// source: suggestionService/suggestpb/suggest.proto

package suggestpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Suggest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Suggest) Reset()         { *m = Suggest{} }
func (m *Suggest) String() string { return proto.CompactTextString(m) }
func (*Suggest) ProtoMessage()    {}
func (*Suggest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{0}
}

func (m *Suggest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Suggest.Unmarshal(m, b)
}
func (m *Suggest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Suggest.Marshal(b, m, deterministic)
}
func (m *Suggest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Suggest.Merge(m, src)
}
func (m *Suggest) XXX_Size() int {
	return xxx_messageInfo_Suggest.Size(m)
}
func (m *Suggest) XXX_DiscardUnknown() {
	xxx_messageInfo_Suggest.DiscardUnknown(m)
}

var xxx_messageInfo_Suggest proto.InternalMessageInfo

func (m *Suggest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Suggest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Suggest) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Suggest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type CreateSuggestRequest struct {
	Suggest              *Suggest `protobuf:"bytes,1,opt,name=suggest,proto3" json:"suggest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSuggestRequest) Reset()         { *m = CreateSuggestRequest{} }
func (m *CreateSuggestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSuggestRequest) ProtoMessage()    {}
func (*CreateSuggestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{1}
}

func (m *CreateSuggestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSuggestRequest.Unmarshal(m, b)
}
func (m *CreateSuggestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSuggestRequest.Marshal(b, m, deterministic)
}
func (m *CreateSuggestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSuggestRequest.Merge(m, src)
}
func (m *CreateSuggestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSuggestRequest.Size(m)
}
func (m *CreateSuggestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSuggestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSuggestRequest proto.InternalMessageInfo

func (m *CreateSuggestRequest) GetSuggest() *Suggest {
	if m != nil {
		return m.Suggest
	}
	return nil
}

type CreateSuggestResponse struct {
	Suggest              *Suggest `protobuf:"bytes,1,opt,name=suggest,proto3" json:"suggest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSuggestResponse) Reset()         { *m = CreateSuggestResponse{} }
func (m *CreateSuggestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSuggestResponse) ProtoMessage()    {}
func (*CreateSuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{2}
}

func (m *CreateSuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSuggestResponse.Unmarshal(m, b)
}
func (m *CreateSuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSuggestResponse.Marshal(b, m, deterministic)
}
func (m *CreateSuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSuggestResponse.Merge(m, src)
}
func (m *CreateSuggestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSuggestResponse.Size(m)
}
func (m *CreateSuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSuggestResponse proto.InternalMessageInfo

func (m *CreateSuggestResponse) GetSuggest() *Suggest {
	if m != nil {
		return m.Suggest
	}
	return nil
}

type ListSuggestRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSuggestRequest) Reset()         { *m = ListSuggestRequest{} }
func (m *ListSuggestRequest) String() string { return proto.CompactTextString(m) }
func (*ListSuggestRequest) ProtoMessage()    {}
func (*ListSuggestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{3}
}

func (m *ListSuggestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSuggestRequest.Unmarshal(m, b)
}
func (m *ListSuggestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSuggestRequest.Marshal(b, m, deterministic)
}
func (m *ListSuggestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSuggestRequest.Merge(m, src)
}
func (m *ListSuggestRequest) XXX_Size() int {
	return xxx_messageInfo_ListSuggestRequest.Size(m)
}
func (m *ListSuggestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSuggestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSuggestRequest proto.InternalMessageInfo

type ListSuggestResponse struct {
	Suggest              *Suggest `protobuf:"bytes,1,opt,name=suggest,proto3" json:"suggest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSuggestResponse) Reset()         { *m = ListSuggestResponse{} }
func (m *ListSuggestResponse) String() string { return proto.CompactTextString(m) }
func (*ListSuggestResponse) ProtoMessage()    {}
func (*ListSuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{4}
}

func (m *ListSuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSuggestResponse.Unmarshal(m, b)
}
func (m *ListSuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSuggestResponse.Marshal(b, m, deterministic)
}
func (m *ListSuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSuggestResponse.Merge(m, src)
}
func (m *ListSuggestResponse) XXX_Size() int {
	return xxx_messageInfo_ListSuggestResponse.Size(m)
}
func (m *ListSuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSuggestResponse proto.InternalMessageInfo

func (m *ListSuggestResponse) GetSuggest() *Suggest {
	if m != nil {
		return m.Suggest
	}
	return nil
}

type DeleteSuggestRequest struct {
	SuggestId            string   `protobuf:"bytes,1,opt,name=suggest_id,json=suggestId,proto3" json:"suggest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSuggestRequest) Reset()         { *m = DeleteSuggestRequest{} }
func (m *DeleteSuggestRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSuggestRequest) ProtoMessage()    {}
func (*DeleteSuggestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{5}
}

func (m *DeleteSuggestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSuggestRequest.Unmarshal(m, b)
}
func (m *DeleteSuggestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSuggestRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSuggestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSuggestRequest.Merge(m, src)
}
func (m *DeleteSuggestRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSuggestRequest.Size(m)
}
func (m *DeleteSuggestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSuggestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSuggestRequest proto.InternalMessageInfo

func (m *DeleteSuggestRequest) GetSuggestId() string {
	if m != nil {
		return m.SuggestId
	}
	return ""
}

type DeleteSuggestResponse struct {
	SuggestId            string   `protobuf:"bytes,1,opt,name=suggest_id,json=suggestId,proto3" json:"suggest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSuggestResponse) Reset()         { *m = DeleteSuggestResponse{} }
func (m *DeleteSuggestResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSuggestResponse) ProtoMessage()    {}
func (*DeleteSuggestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_31a3567326bb37cb, []int{6}
}

func (m *DeleteSuggestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSuggestResponse.Unmarshal(m, b)
}
func (m *DeleteSuggestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSuggestResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSuggestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSuggestResponse.Merge(m, src)
}
func (m *DeleteSuggestResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSuggestResponse.Size(m)
}
func (m *DeleteSuggestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSuggestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSuggestResponse proto.InternalMessageInfo

func (m *DeleteSuggestResponse) GetSuggestId() string {
	if m != nil {
		return m.SuggestId
	}
	return ""
}

func init() {
	proto.RegisterType((*Suggest)(nil), "suggest.Suggest")
	proto.RegisterType((*CreateSuggestRequest)(nil), "suggest.CreateSuggestRequest")
	proto.RegisterType((*CreateSuggestResponse)(nil), "suggest.CreateSuggestResponse")
	proto.RegisterType((*ListSuggestRequest)(nil), "suggest.ListSuggestRequest")
	proto.RegisterType((*ListSuggestResponse)(nil), "suggest.ListSuggestResponse")
	proto.RegisterType((*DeleteSuggestRequest)(nil), "suggest.DeleteSuggestRequest")
	proto.RegisterType((*DeleteSuggestResponse)(nil), "suggest.DeleteSuggestResponse")
}

func init() {
	proto.RegisterFile("suggestionService/suggestpb/suggest.proto", fileDescriptor_31a3567326bb37cb)
}

var fileDescriptor_31a3567326bb37cb = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x25, 0xf9, 0xfa, 0xb5, 0x64, 0x82, 0x45, 0xc6, 0x54, 0x42, 0xb5, 0x22, 0x39, 0xa9, 0x87,
	0x2a, 0x15, 0xbd, 0xdb, 0xc6, 0x83, 0x22, 0x1e, 0xda, 0x9b, 0x1e, 0x24, 0x35, 0x43, 0x59, 0xa8,
	0x4d, 0xcc, 0x6e, 0xfd, 0xf5, 0x1e, 0x24, 0x9b, 0xc9, 0x92, 0xb4, 0x51, 0xd0, 0xdb, 0xcc, 0xdb,
	0x99, 0xf7, 0xde, 0xbe, 0x5d, 0x38, 0x95, 0xeb, 0xc5, 0x82, 0xa4, 0x12, 0xc9, 0x6a, 0x46, 0xd9,
	0x87, 0x78, 0xa5, 0x73, 0x46, 0xd2, 0x79, 0x59, 0x0d, 0xd3, 0x2c, 0x51, 0x09, 0x76, 0xb8, 0x0d,
	0x9e, 0xa1, 0x33, 0x2b, 0x4a, 0xec, 0x82, 0x2d, 0x62, 0xdf, 0x3a, 0xb6, 0x4e, 0x9c, 0xa9, 0x2d,
	0x62, 0xf4, 0xe0, 0xff, 0xed, 0x5b, 0x24, 0x96, 0xbe, 0xad, 0xa1, 0xa2, 0xc1, 0x7d, 0x68, 0x87,
	0xa4, 0x72, 0xf8, 0x9f, 0x86, 0xb9, 0x43, 0x84, 0x56, 0x18, 0x29, 0xf2, 0x5b, 0x1a, 0xd5, 0x75,
	0x30, 0x06, 0x6f, 0x92, 0x51, 0xa4, 0x88, 0x25, 0xa6, 0xf4, 0xbe, 0xce, 0x95, 0xce, 0xa0, 0xd4,
	0xd7, 0x72, 0xee, 0x68, 0x77, 0x58, 0xda, 0x2b, 0x27, 0x8d, 0xc1, 0x09, 0xf4, 0x36, 0x38, 0x64,
	0x9a, 0xac, 0x24, 0xfd, 0x8a, 0xc4, 0x03, 0x7c, 0x10, 0x52, 0xd5, 0x6d, 0x04, 0x37, 0xb0, 0x57,
	0x43, 0xff, 0x40, 0x7c, 0x05, 0x5e, 0x48, 0x4b, 0xda, 0xba, 0xe1, 0x00, 0x80, 0x47, 0x5e, 0x4c,
	0xa6, 0x0e, 0x23, 0x77, 0x71, 0x70, 0x0d, 0xbd, 0x8d, 0x35, 0xd6, 0xfe, 0x79, 0x6f, 0xf4, 0x69,
	0x41, 0x97, 0x57, 0xf8, 0x85, 0xf1, 0x11, 0x76, 0x6a, 0xf9, 0xe0, 0xc0, 0xb8, 0x6d, 0xca, 0xbe,
	0x7f, 0xf4, 0xdd, 0x31, 0x3b, 0xb8, 0x07, 0xb7, 0x12, 0x0a, 0x1e, 0x98, 0xf1, 0xed, 0x00, 0xfb,
	0x87, 0xcd, 0x87, 0x05, 0xd3, 0x85, 0x95, 0x7b, 0xab, 0x5d, 0xb3, 0xe2, 0xad, 0x29, 0xb5, 0x8a,
	0xb7, 0xc6, 0x74, 0xc6, 0xee, 0x93, 0x63, 0x3e, 0xf4, 0xbc, 0xad, 0x7f, 0xf2, 0xe5, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x84, 0x14, 0xea, 0x0c, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SuggestServiceClient is the client API for SuggestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuggestServiceClient interface {
	CreateSuggest(ctx context.Context, in *CreateSuggestRequest, opts ...grpc.CallOption) (*CreateSuggestResponse, error)
	ListSuggest(ctx context.Context, in *ListSuggestRequest, opts ...grpc.CallOption) (SuggestService_ListSuggestClient, error)
	DeleteSuggest(ctx context.Context, in *DeleteSuggestRequest, opts ...grpc.CallOption) (*DeleteSuggestResponse, error)
}

type suggestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuggestServiceClient(cc grpc.ClientConnInterface) SuggestServiceClient {
	return &suggestServiceClient{cc}
}

func (c *suggestServiceClient) CreateSuggest(ctx context.Context, in *CreateSuggestRequest, opts ...grpc.CallOption) (*CreateSuggestResponse, error) {
	out := new(CreateSuggestResponse)
	err := c.cc.Invoke(ctx, "/suggest.SuggestService/CreateSuggest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suggestServiceClient) ListSuggest(ctx context.Context, in *ListSuggestRequest, opts ...grpc.CallOption) (SuggestService_ListSuggestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SuggestService_serviceDesc.Streams[0], "/suggest.SuggestService/ListSuggest", opts...)
	if err != nil {
		return nil, err
	}
	x := &suggestServiceListSuggestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SuggestService_ListSuggestClient interface {
	Recv() (*ListSuggestResponse, error)
	grpc.ClientStream
}

type suggestServiceListSuggestClient struct {
	grpc.ClientStream
}

func (x *suggestServiceListSuggestClient) Recv() (*ListSuggestResponse, error) {
	m := new(ListSuggestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *suggestServiceClient) DeleteSuggest(ctx context.Context, in *DeleteSuggestRequest, opts ...grpc.CallOption) (*DeleteSuggestResponse, error) {
	out := new(DeleteSuggestResponse)
	err := c.cc.Invoke(ctx, "/suggest.SuggestService/DeleteSuggest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuggestServiceServer is the server API for SuggestService service.
type SuggestServiceServer interface {
	CreateSuggest(context.Context, *CreateSuggestRequest) (*CreateSuggestResponse, error)
	ListSuggest(*ListSuggestRequest, SuggestService_ListSuggestServer) error
	DeleteSuggest(context.Context, *DeleteSuggestRequest) (*DeleteSuggestResponse, error)
}

// UnimplementedSuggestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSuggestServiceServer struct {
}

func (*UnimplementedSuggestServiceServer) CreateSuggest(ctx context.Context, req *CreateSuggestRequest) (*CreateSuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSuggest not implemented")
}
func (*UnimplementedSuggestServiceServer) ListSuggest(req *ListSuggestRequest, srv SuggestService_ListSuggestServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSuggest not implemented")
}
func (*UnimplementedSuggestServiceServer) DeleteSuggest(ctx context.Context, req *DeleteSuggestRequest) (*DeleteSuggestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSuggest not implemented")
}

func RegisterSuggestServiceServer(s *grpc.Server, srv SuggestServiceServer) {
	s.RegisterService(&_SuggestService_serviceDesc, srv)
}

func _SuggestService_CreateSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestServiceServer).CreateSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/suggest.SuggestService/CreateSuggest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestServiceServer).CreateSuggest(ctx, req.(*CreateSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SuggestService_ListSuggest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSuggestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuggestServiceServer).ListSuggest(m, &suggestServiceListSuggestServer{stream})
}

type SuggestService_ListSuggestServer interface {
	Send(*ListSuggestResponse) error
	grpc.ServerStream
}

type suggestServiceListSuggestServer struct {
	grpc.ServerStream
}

func (x *suggestServiceListSuggestServer) Send(m *ListSuggestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SuggestService_DeleteSuggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSuggestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuggestServiceServer).DeleteSuggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/suggest.SuggestService/DeleteSuggest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuggestServiceServer).DeleteSuggest(ctx, req.(*DeleteSuggestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SuggestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "suggest.SuggestService",
	HandlerType: (*SuggestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSuggest",
			Handler:    _SuggestService_CreateSuggest_Handler,
		},
		{
			MethodName: "DeleteSuggest",
			Handler:    _SuggestService_DeleteSuggest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSuggest",
			Handler:       _SuggestService_ListSuggest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "suggestionService/suggestpb/suggest.proto",
}
